(function(){
const DB={players:[
['Bellingham','England','MID','diamond',93,91,84,92,89],['Mbappe','France','FWD','diamond',95,96,55,88,98],['Messi','Argentina','FWD','diamond',94,93,50,96,97],['Vinicius Jr','Brazil','FWD','diamond',92,94,48,82,97],['Haaland','Norway','FWD','diamond',92,97,60,80,78],['Kane','England','FWD','goldR',90,93,62,91,82],['Saka','England','FWD','goldR',88,88,68,80,91],['Musiala','Germany','MID','goldR',88,86,61,78,93],['Pedri','Spain','MID','goldR',87,82,70,80,90],['Valverde','Uruguay','MID','goldR',87,84,82,82,80],['Rodri','Spain','MID','goldR',91,78,92,93,74],['Van Dijk','Netherlands','DEF','goldR',90,66,95,90,60],['Griezmann','France','FWD','goldR',88,87,70,91,88],['Son','South Korea','FWD','goldR',88,90,55,88,86],['Pulisic','USA','FWD','silver',83,82,50,76,87],['Davies','Canada','DEF','silver',84,78,80,74,90],['Gimenez','Mexico','FWD','silver',82,84,54,70,78],['Mitoma','Japan','MID','silver',83,80,56,72,89],['Enzo','Argentina','MID','silver',84,78,79,75,78],['Gakpo','Netherlands','FWD','silver',84,84,57,76,82],['Ramos','Portugal','FWD','silver',82,84,56,68,76],['McKennie','USA','MID','silver',80,76,77,76,74],['Caicedo','Ecuador','MID','silver',82,70,84,74,72],['Kudus','Ghana','MID','silver',82,81,61,72,86],['Araujo','Uruguay','DEF','silver',85,63,90,74,61],['Martinelli','Brazil','FWD','silver',84,83,52,70,90],['Turner','USA','GK','common',76,35,78,70,38],['Alvarez','Mexico','MID','common',78,66,81,76,59],['Johnston','Canada','DEF','common',76,55,78,70,64],['Ito','Japan','FWD','common',78,77,48,72,84],['Moore','England','MID','common',74,72,66,64,71],['Garcia','Spain','DEF','common',75,57,77,67,65],['Silva','Brazil','MID','common',76,74,62,66,76],['Muller','Germany','MID','common',77,76,56,82,72],['Costa','Portugal','GK','common',78,32,81,66,35],['Kim','South Korea','DEF','common',79,48,84,70,55],['Mensah','Ghana','DEF','common',74,50,76,63,66],['Santos','Uruguay','MID','common',75,70,68,65,72],['Lopez','Argentina','FWD','common',76,77,45,66,75],['Dumfries','Netherlands','DEF','common',80,70,82,74,76],['Diallo','Senegal','FWD','common',75,76,45,62,82],['Kovacs','Croatia','MID','common',77,70,71,77,69]
],rarityValue:{common:[5,50],silver:[50,300],goldR:[300,2500],diamond:[2500,25000]},odds:{standard:{common:70,silver:22,goldR:7,diamond:1},rare:{common:45,silver:38,goldR:14,diamond:3}}};
const S={get username(){return sessionStorage.cl_username||''},set username(v){sessionStorage.cl_username=v},get lld(){return +(sessionStorage.cl_lld||750)},set lld(v){sessionStorage.cl_lld=Math.max(0,Math.round(v))},get standard(){return +(sessionStorage.cl_standard||3)},set standard(v){sessionStorage.cl_standard=Math.max(0,v)},get rare(){return +(sessionStorage.cl_rare||1)},set rare(v){sessionStorage.cl_rare=Math.max(0,v)},get inv(){try{return JSON.parse(sessionStorage.cl_inv||'[]')}catch(e){return[]}},set inv(v){sessionStorage.cl_inv=JSON.stringify(v)},get market(){try{return JSON.parse(localStorage.cl_market||'[]')}catch(e){return[]}},set market(v){localStorage.cl_market=JSON.stringify(v)}};
function init(){document.body.classList.add('grain');document.body.insertAdjacentHTML('beforeend','<div class="stadium"></div><div class="toast" id="toast"></div><div class="modal" id="modal"><div class="modalBox" id="modalBox"></div></div>');nav();route();}
function nav(){const el=document.querySelector('[data-nav]');if(!el)return; const page=location.pathname.split('/').pop()||'index.html';el.innerHTML=`<div class="brand"><span class="mark">CL</span><span>Case League</span></div><div class="nav"><a class="${page==='hub.html'?'active':''}" href="hub.html">Home</a><a class="${page==='store.html'?'active':''}" href="store.html">Store</a><a class="${page==='open.html'?'active':''}" href="open.html">Open</a><a class="${page==='inventory.html'?'active':''}" href="inventory.html">Inventory</a><a class="${page==='match.html'?'active':''}" href="match.html">Quick Match</a><a class="${page==='market.html'?'active':''}" href="market.html">Marketplace</a><a class="${page==='odds.html'?'active':''}" href="odds.html">Odds</a></div><div class="chips"><span class="chip">${S.standard} Standard</span><span class="chip">${S.rare} Rare</span><span class="chip">◈ ${S.lld} LLD</span><span class="chip">${S.username||'Guest'}</span></div>`}
function route(){if(!document.body.dataset.page)return;if(document.body.dataset.page!=='login'&&!S.username){location.href='../index.html';return}const p=document.body.dataset.page;({login,hub,store,open,inventory,market,match,odds}[p]||(()=>{}))();}
function login(){const f=document.getElementById('loginForm');f.onsubmit=e=>{e.preventDefault();const u=document.getElementById('username').value.trim();if(u.length<2)return toast('Enter a username');if(!sessionStorage.cl_seen){S.standard=3;S.rare=1;S.lld=750;S.inv=[];sessionStorage.cl_seen='1'}S.username=u;location.href='pages/hub.html'};}
function hub(){q('#stats').innerHTML=`<div class="stat"><b>${S.inv.length}</b><span>Players Owned</span></div><div class="stat"><b>${S.standard+S.rare}</b><span>Cases Ready</span></div><div class="stat"><b>${estimate(S.inv)}</b><span>Collection LLD</span></div>`;q('#featured').innerHTML=sample(DB.players,6).map(p=>card(make(p),false)).join('')}
function store(){q('#caseGrid').innerHTML=[['standard','Standard Case','£1.70','6 players, at least 3 Common and 1 Silver+','⚽'],['rare','Rare Case','£2.50','6 players, at least 2 Common and 2 Silver+','🏆']].map(c=>`<div class="card caseCard"><div class="caseIcon">${c[4]}</div><h2>${c[1]}</h2><p>${c[3]}</p><div class="price">${c[2]}</div><button class="btn gold" onclick="CL.buy('${c[0]}')">Buy with LLD</button></div>`).join('')}
function buy(t){let cost=t==='standard'?170:250;if(S.lld<cost)return toast('Not enough LLD in demo balance');S.lld-=cost;if(t==='standard')S.standard++;else S.rare++;nav();toast('Case purchased');}
function open(){let selected='standard';const render=()=>{q('#caseInfo').innerHTML=selected==='standard'?'Standard Case: at least 3 Common and 1 Silver+':'Rare Case: at least 2 Common and 2 Silver+';q('#openBtn').textContent=`Open ${selected==='standard'?'Standard':'Rare'} Case`;q('#tabs').innerHTML=`<button class="tab ${selected==='standard'?'active':''}" data-t="standard">Standard</button><button class="tab ${selected==='rare'?'active':''}" data-t="rare">Rare</button>`;qa('#tabs .tab').forEach(b=>b.onclick=()=>{selected=b.dataset.t;render()});fillTrack(randomFill(42));};q('#openBtn').onclick=()=>openCase(selected);render();}
function openCase(type){if(type==='standard'&&S.standard<1)return toast('No Standard Cases left');if(type==='rare'&&S.rare<1)return toast('No Rare Cases left');if(type==='standard')S.standard--;else S.rare--;nav();const real=rollCase(type);const fill=randomFill(36);fill.splice(24,0,...real);fillTrack(fill);const tr=q('#track');tr.style.transition='none';tr.style.transform='translateX(0)';requestAnimationFrame(()=>{tr.style.transition='transform 3.7s cubic-bezier(.12,.7,.12,1)';tr.style.transform='translateX(-3220px)'});setTimeout(()=>{const inv=S.inv;real.forEach(x=>inv.push(x));S.inv=inv;showResults(real,type)},3900)}
function fillTrack(items){q('#track').innerHTML=items.map(x=>`<div class="miniCard ${x.rarity}"><div><div class="ball">${emoji(x)}</div><b>${x.name}</b><br><span class="rarity ${x.rarity}">${label(x.rarity)}</span></div></div>`).join('')}
function showResults(items,type){const best=items.sort((a,b)=>rank(b.rarity)-rank(a.rarity))[0];modal(`<div class="eyebrow">${type} case opened</div><h2>${label(best.rarity)} pull secured</h2><p>Six players have been saved to your inventory. Total estimated value: <b>${estimate(items)} LLD</b>.</p><div class="grid">${items.map(x=>card(x,true)).join('')}</div><div class="btns"><a class="btn gold" href="inventory.html">View Inventory</a><button class="btn ghost" onclick="CL.closeModal()">Open Another</button></div>`)}
function inventory(){let f='all';const draw=()=>{let items=S.inv.filter(x=>f==='all'||x.rarity===f);q('#invStats').innerHTML=`<div class="stat"><b>${S.inv.length}</b><span>Total</span></div><div class="stat"><b>${estimate(S.inv)}</b><span>Value LLD</span></div><div class="stat"><b>${S.inv.filter(x=>['goldR','diamond'].includes(x.rarity)).length}</b><span>Gold+</span></div>`;q('#filters').innerHTML=['all','common','silver','goldR','diamond'].map(x=>`<button class="filter ${f===x?'active':''}" data-f="${x}">${x==='goldR'?'Gold':cap(x)}</button>`).join('');qa('#filters button').forEach(b=>b.onclick=()=>{f=b.dataset.f;draw()});q('#invGrid').innerHTML=items.length?items.map((x,i)=>card(x,true,`<button class="btn ghost" onclick="CL.listItem('${x.id}')">List</button>`)).join(''):`<div class="notice">No players here yet. Open a case to build your squad.</div>`};draw();}
function listItem(id){const inv=S.inv;const item=inv.find(x=>x.id===id);if(!item)return;const price=suggest(item);const html=`<h2>List ${item.name}</h2>${card(item,true)}<p>Suggested market price: <b>${price} LLD</b>. Admin receives 20% when sold.</p><input id="listPrice" class="input" type="number" value="${price}" min="1"><div class="btns"><button class="btn gold" onclick="CL.confirmList('${id}')">List Player</button><button class="btn ghost" onclick="CL.closeModal()">Cancel</button></div>`;modal(html)}
function confirmList(id){const inv=S.inv;const idx=inv.findIndex(x=>x.id===id);if(idx<0)return;const item=inv.splice(idx,1)[0];item.price=+(q('#listPrice').value||suggest(item));item.seller=S.username;item.listedAt=Date.now();S.inv=inv;const m=S.market;m.unshift(item);S.market=m;closeModal();toast('Player listed on marketplace');inventory();}
function market(){const m=S.market;q('#marketGrid').innerHTML=m.length?m.map((x,i)=>card(x,true,`<button class="btn gold" onclick="CL.buyMarket('${x.id}')">Buy ${x.price} LLD</button>`)).join(''):`<div class="notice">Marketplace is empty. List a player from your inventory.</div>`;}
function buyMarket(id){const m=S.market;const i=m.findIndex(x=>x.id===id);if(i<0)return;const item=m[i];if(item.seller===S.username)return toast('You cannot buy your own listing');if(S.lld<item.price)return toast('Not enough LLD');S.lld-=item.price;const admin=Math.round(item.price*.2);item.boughtAt=Date.now();delete item.price;delete item.seller;S.inv=[...S.inv,item];m.splice(i,1);S.market=m;nav();toast(`Bought player. Admin fee: ${admin} LLD`);market();}
function match(){let selected=[];const draw=()=>{const inv=S.inv;q('#pickGrid').innerHTML=inv.length?inv.map(x=>card(x,true,`<button class="btn ghost">Select</button>`,'selectable '+(selected.includes(x.id)?'selected':''))).join(''):`<div class="notice">Open cases first to get players for Quick Match.</div>`;qa('.selectable').forEach((el,i)=>{el.onclick=()=>{const id=inv[i].id;if(selected.includes(id))selected=selected.filter(v=>v!==id);else if(selected.length<3)selected.push(id);else toast('Only 3 players');draw();}});q('#selectedCount').textContent=selected.length};q('#startMatch').onclick=()=>{if(selected.length!==3)return toast('Select exactly 3 players');simulate(selected.map(id=>S.inv.find(x=>x.id===id)))};draw();}
function simulate(team){const opp=[make(pickByRarity('silver')),make(pickByRarity('silver')),make(pickByRarity(Math.random()>.6?'goldR':'common'))];const a=power(team),b=power(opp);let us=0,them=0,minute=0;q('#score').textContent='0 - 0';q('#feed').innerHTML='';const timer=setInterval(()=>{minute+=6;const chance=Math.random()*100;if(chance<23){const our=(Math.random()*a)/(a+b)>Math.random()*.55;if(our)us++;else them++;line(`${minute}' ${our?'Case League FC':'World XI'} scores after a ${our?'flair':'counter'} move.`);q('#score').textContent=`${us} - ${them}`;}else if(chance<48){line(`${minute}' ${Math.random()>.5?'Big defensive block':'Midfield battle wins possession'}.`)}else if(chance<62){line(`${minute}' ${Math.random()>.5?'Skill move beats two players':'Long shot flashes wide'}.`)}if(minute>=90){clearInterval(timer);const reward=us>them?Math.round(60+Math.random()*140):them===us?35:10;S.lld+=reward;nav();line(`Full time. You earned ${reward} LLD.`)}},180)}
function odds(){q('#oddsBox').innerHTML=`<div class="grid"><div class="card"><h2>Standard Case</h2>${oddsRows(DB.odds.standard)}<p>Guarantees 3 Common and 1 Silver+.</p></div><div class="card"><h2>Rare Case</h2>${oddsRows(DB.odds.rare)}<p>Guarantees 2 Common and 2 Silver+.</p></div></div>`;q('#pool').innerHTML=DB.players.map(p=>card(make(p),false)).join('')}
function oddsRows(o){return Object.entries(o).map(([k,v])=>`<p><span class="rarity ${k}">${label(k)}</span> ${v}%</p><div class="bar"><i style="width:${v}%"></i></div>`).join('')}
function rollCase(type){const out=[];if(type==='standard'){for(let i=0;i<3;i++)out.push(make(pickByRarity('common')));out.push(make(pickWeighted({silver:80,goldR:17,diamond:3})));for(let i=0;i<2;i++)out.push(make(pickWeighted(DB.odds.standard)));}else{for(let i=0;i<2;i++)out.push(make(pickByRarity('common')));for(let i=0;i<2;i++)out.push(make(pickByRarity('silver')));out.push(make(pickWeighted({silver:60,goldR:35,diamond:5})));out.push(make(pickWeighted({goldR:80,diamond:20})));}return shuffle(out)}
function make(p){const [name,country,pos,rarity,ovr,atk,def,exp,flair]=p;const range=DB.rarityValue[rarity];return{id:cryptoId(),name,country,pos,rarity,ovr,atk,def,exp,flair,value:rand(range[0],range[1]),date:new Date().toLocaleDateString()}}
function pickByRarity(r){return sample(DB.players.filter(p=>p[3]===r),1)[0]}function pickWeighted(o){let total=Object.values(o).reduce((a,b)=>a+b,0),n=Math.random()*total;for(const [k,v]of Object.entries(o)){n-=v;if(n<=0)return k}return 'common'}function randomFill(n){return Array.from({length:n},()=>make(pickByRarity(pickWeighted({common:62,silver:26,goldR:10,diamond:2}))))}
function card(x,full,extra='',cls=''){return `<div class="player ${x.rarity} ${cls}"><div class="face">${emoji(x)}</div><div class="name">${x.name}</div><div class="meta"><span>${x.country} · ${x.pos}</span><span>OVR ${x.ovr}</span></div><span class="rarity ${x.rarity}">${label(x.rarity)}</span>${full?`<div class="bars"><small>Attack ${x.atk}</small><div class="bar"><i style="width:${x.atk}%"></i></div><small>Defence ${x.def}</small><div class="bar"><i style="width:${x.def}%"></i></div><small>Experience ${x.exp}</small><div class="bar"><i style="width:${x.exp}%"></i></div><small>Flair ${x.flair}</small><div class="bar"><i style="width:${x.flair}%"></i></div></div><p>Value: <b>${x.price||x.value} LLD</b></p>${extra}`:''}</div>`}
function emoji(x){return x.pos==='GK'?'🧤':x.pos==='DEF'?'🛡️':x.pos==='MID'?'🎯':'⚽'}function label(r){return r==='goldR'?'Gold':cap(r)}function cap(s){return s.charAt(0).toUpperCase()+s.slice(1)}function rank(r){return{common:1,silver:2,goldR:3,diamond:4}[r]||0}function suggest(x){return Math.round((x.value*(1+rank(x.rarity)*.25)+x.ovr*rank(x.rarity))*1.1)}function estimate(arr){return arr.reduce((a,b)=>a+(b.price||b.value||0),0)}function power(arr){return arr.reduce((s,x)=>s+x.atk*1.1+x.def*.9+x.exp*.85+x.flair*.75+x.ovr,0)}function line(t){q('#feed').insertAdjacentHTML('afterbegin',`<div class="feedLine">${t}</div>`)}function modal(h){q('#modalBox').innerHTML=h;q('#modal').classList.add('show')}function closeModal(){q('#modal').classList.remove('show')}function toast(t){const d=document.createElement('div');d.textContent=t;q('#toast').appendChild(d);setTimeout(()=>d.remove(),3200)}function q(s){return document.querySelector(s)}function qa(s){return [...document.querySelectorAll(s)]}function sample(a,n){return shuffle([...a]).slice(0,n)}function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function rand(a,b){return Math.floor(a+Math.random()*(b-a+1))}function cryptoId(){return 'cl_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
window.CL={buy,openCase,closeModal,listItem,confirmList,buyMarket};document.addEventListener('DOMContentLoaded',init);
})();
